name: Build and publish a Docker image

on: [push]

jobs:
  build:
    name: Build & push docker image
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and push Husky Docker image
        uses: docker/build-push-action@v4
    
 

